# -*- coding: utf-8 -*-
"""FarmTechIrrigation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWCOevOQAPZQQFVdRc6AMcsH6vsMjycD
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

dataset_path = "random_irrigation_dataset.csv"
df = pd.read_csv(dataset_path)

X = df[["temperature", "pressure", "altitude", "soilmoisture"]]
y = df["class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"\nAcurácia do modelo: {accuracy:.2f}")
print("\nRelatório de Classificação:")
print(report)

new_data = pd.DataFrame({
    "temperature": [25, 35, 20],
    "pressure": [1010, 1000, 950],
    "altitude": [100, 300, 200],
    "soilmoisture": [0.2, 0.8, 0.4],
})

predictions = rf_model.predict(new_data)
new_data["class"] = predictions

print("\nPrevisões para novos dados:")
print(new_data)